"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAnalyticsStoragePaths = exports.loadAnalyticsIdentity = exports.parseRetryAfterMs = exports.isRetryableStatus = exports.isPermanentStatus = exports.getRetryDelayMs = exports.getSafeHostname = exports.normalizePlatform = exports.normalizeArchitecture = exports.trackApplicationError = exports.getAnalyticsErrorCodeForScope = exports.registerAnalyticsIpcHandlers = exports.createAnalyticsEvent = exports.ANALYTICS_CONFIG = exports.AnalyticsClient = void 0;
var analytics_client_js_1 = require("./analytics-client.js");
Object.defineProperty(exports, "AnalyticsClient", { enumerable: true, get: function () { return analytics_client_js_1.AnalyticsClient; } });
var analytics_config_js_1 = require("./analytics-config.js");
Object.defineProperty(exports, "ANALYTICS_CONFIG", { enumerable: true, get: function () { return analytics_config_js_1.ANALYTICS_CONFIG; } });
var analytics_events_js_1 = require("./analytics-events.js");
Object.defineProperty(exports, "createAnalyticsEvent", { enumerable: true, get: function () { return analytics_events_js_1.createAnalyticsEvent; } });
var analytics_ipc_js_1 = require("./analytics-ipc.js");
Object.defineProperty(exports, "registerAnalyticsIpcHandlers", { enumerable: true, get: function () { return analytics_ipc_js_1.registerAnalyticsIpcHandlers; } });
Object.defineProperty(exports, "getAnalyticsErrorCodeForScope", { enumerable: true, get: function () { return analytics_ipc_js_1.getAnalyticsErrorCodeForScope; } });
Object.defineProperty(exports, "trackApplicationError", { enumerable: true, get: function () { return analytics_ipc_js_1.trackApplicationError; } });
var analytics_platform_js_1 = require("./analytics-platform.js");
Object.defineProperty(exports, "normalizeArchitecture", { enumerable: true, get: function () { return analytics_platform_js_1.normalizeArchitecture; } });
Object.defineProperty(exports, "normalizePlatform", { enumerable: true, get: function () { return analytics_platform_js_1.normalizePlatform; } });
var analytics_privacy_js_1 = require("./analytics-privacy.js");
Object.defineProperty(exports, "getSafeHostname", { enumerable: true, get: function () { return analytics_privacy_js_1.getSafeHostname; } });
var analytics_retry_js_1 = require("./analytics-retry.js");
Object.defineProperty(exports, "getRetryDelayMs", { enumerable: true, get: function () { return analytics_retry_js_1.getRetryDelayMs; } });
Object.defineProperty(exports, "isPermanentStatus", { enumerable: true, get: function () { return analytics_retry_js_1.isPermanentStatus; } });
Object.defineProperty(exports, "isRetryableStatus", { enumerable: true, get: function () { return analytics_retry_js_1.isRetryableStatus; } });
Object.defineProperty(exports, "parseRetryAfterMs", { enumerable: true, get: function () { return analytics_retry_js_1.parseRetryAfterMs; } });
var analytics_storage_js_1 = require("./analytics-storage.js");
Object.defineProperty(exports, "loadAnalyticsIdentity", { enumerable: true, get: function () { return analytics_storage_js_1.loadAnalyticsIdentity; } });
Object.defineProperty(exports, "getAnalyticsStoragePaths", { enumerable: true, get: function () { return analytics_storage_js_1.getAnalyticsStoragePaths; } });
//# sourceMappingURL=index.js.map